import random
print("""\n\"Number Guess Game\"\nCreated by \"Reza Rafiee\".05-Feb-22
In this game,a number is generated by system and you should guess it
The number would be an \"Even\" one between \"0\" and \"20\"
But be careful;You've got only \"5\" attempts!""")
RandomNumber = str(random.randrange(0, 21, 2))
Answer = "Y"
while Answer == "Y":
    Guesses = 0
    Go = input("\nIf you are ready,Type \"Go\"\n").capitalize()
    while Go != "Go":
        Go = input("Type \"Go\" please\n").capitalize()
    UserGuess = input("\nMake your first guess : ")
    while UserGuess != RandomNumber:
        if Guesses != 4:
            UserGuess = input("Try again : ")
            Guesses += 1
        else:
            print("Sorry you couldn't guess!")
            Answer = input("Type \"Q\" to quit\n").capitalize()
            while Answer != "Q":
                Answer = input("Type \"Q\" please\n").capitalize()
            print("Thanks for playing , BYE \U0001f609\u2764\ufe0f")
            break
    else:
        print(f"""CORRECT...!!!\U0001f60d
The generated number is : {RandomNumber}""")
        print("\nThanks for playing \U0001f60a\u2764\ufe0f")
        print("-----------------------")
        Answer = input("""Would you like to play again?
Type \"Y\" or \"N\"\n""").capitalize()
        while Answer not in ("Y", "N"):
            Answer = input("Type \"Y\" or \"N\" please\n").capitalize()
        if Answer == "N":
            print("Thanks for playing , BYE \U0001f609\u2764\ufe0f")
